#1280 feat/add placeholder for empty pic
vuestorefront/storefront-ui pull request #1387
Opened 2020-08-31 20:19 UTC by AdamPawlinski

# Related issue

Closes #1280 

# Scope of work
Continue work from https://github.com/DivanteLtd/storefront-ui/pull/1339 
Fix after CR and add class to icon.

# Screenshots of visual changes
![image](https://user-images.githubusercontent.com/32042425/91764603-e32b8e80-ebd7-11ea-845f-f2bb90dec614.png)

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented

2020-08-31 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1387) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: AdamPawlinski<br/>:x: mohammad-k8<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/storefront-ui?pullRequest=1387) it.</sub>

2020-09-01 04:54 UTC, mohammad-k8 submitted a review, later dismissed
Thanks @AdamPawlinski for completing this.

2020-09-01 06:21 UTC, AdamPawlinski commented
@mohammad-k8 No problem :)

2020-09-08 08:22 UTC, filrak submitted a review, later dismissed

2020-09-15 06:07 UTC, justyna-13 requested changes

2020-09-15 06:07 UTC, justyna-13 commented on packages/shared/styles/components/molecules/SfSelect.scss
> -<<<<<<< HEAD
Conflict hasn't been resolved :)

2020-12-14 08:19 UTC, mayashavin commented on packages/vue/src/components/organisms/SfStoreLocator/_internal/SfStore.vue
> +          :width="82"
`width` should not be a fixed manual code. same with `height`. Maybe improve it?

2021-01-07 08:45 UTC, mayashavin approved these changes

2021-01-07 09:03 UTC, justyna-13 reviewed
good job @AdamPawlinski :slightly_smiling_face:   see my comment :)

2021-01-07 09:03 UTC, justyna-13 commented on packages/vue/src/components/organisms/SfStoreLocator/_internal/SfStore.vue
> +        <SfImage v-if="picture" :src="picture" :alt="`${name} picture`" />
it should get string instead of object :)

2021-01-07 12:28 UTC, mayashavin commented on packages/vue/src/components/organisms/SfStoreLocator/_internal/SfStore.vue
> +          :width="82"
yes it is :)

2021-01-07 15:46 UTC, mayashavin approved these changes

2021-01-07 15:50 UTC, merged