feat: SfColorPicker on product page
vuestorefront/storefront-ui pull request #1518
Opened 2020-11-06 07:41 UTC by justyna-13

# Related issue
Closes #949 

# Scope of work
SfColorPicker added on product page 

# Screenshots of visual changes
![Zrzut ekranu z 2020-11-06 08-39-56](https://user-images.githubusercontent.com/46591755/98339284-c2364e00-200b-11eb-8963-87e115d6a4c4.png)
![Zrzut ekranu z 2020-11-06 08-40-12](https://user-images.githubusercontent.com/46591755/98339289-c498a800-200b-11eb-8e33-91a6dd755710.png)
![Zrzut ekranu z 2020-11-06 08-40-24](https://user-images.githubusercontent.com/46591755/98339296-c6626b80-200b-11eb-9299-7c793f34852e.png)

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-11-23 11:20 UTC, AdamPawlinski reviewed
However there is no such design on figma, but I wonder if the color picker should be aligned to the right edge of gallery or picture when you are on mobile mode. Or maybe gallery should take 100% width: 
![image](https://user-images.githubusercontent.com/32042425/99955624-fbe5b380-2d84-11eb-96b5-669e81ef4191.png)

What do you think? @justyna-13

2021-03-03 08:21 UTC, Baroshem requested changes
Overall it looks good, some small adjustments from my side ;) Also, please resolve conflicts.

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
> +      handleSelectedColor(color) {
Two things here:

1. Maybe small naming convention change would make this method easier to understand (`color` => `selectedColor`, `el` => `color`
2. Currently we do not have many colors however in the future there may be more. Here we are looking for one specific color and we are toggling its value and for anything else we are setting `false`. This is not very efficient. The better approach in my opinion would be to find one (first) element of the colors array and toggle it's value.

```js
      handleSelectedColor(selectedColor) {
        const pickedColorIndex = this.colors.findIndex(color => color.label === selectedColor.label);  // here we are returning first element index that matches the query

        this.colors[pickedColorIndex].selected = !this.colors[pickedColorIndex].selected
      },
```

What do you think?

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
> +      handleSelectedColor(color) {
Here the same as in the previous comment

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
> +      handleSelectedColor(color) {
Same here

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
> +      handleSelectedColor(color) {
refactor

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
> +            @click="handleSelectedColor(i)"
Can't we just emit the event with color here?
```suggestion
            @click="$emit("click:colors", color)"
```

2021-03-03 08:21 UTC, Baroshem commented on packages/vue/src/examples/pages/product/Product.vue
> +          @click="selectColor(i)"
I cannot find this method. Was it developed earlier?

2021-08-06 21:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1518) before we can accept your contribution.<br/><hr/>**Justyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1518) it.</sub>

2022-03-17 10:31 UTC, closed without merging