fix: SfSelect remove outline property
vuestorefront/storefront-ui pull request #1533
Opened 2020-11-16 14:16 UTC by AdamPawlinski

# Related issue
Closes #1531 

# Scope of work
Removed outline: none property from SfSelect styling to make outline focus appearing when using keyboard.

# Screenshots of visual changes
![image](https://user-images.githubusercontent.com/32042425/99262754-a0647480-281e-11eb-8746-5aad4d58d4fd.png)

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-11-18 10:07 UTC, justyna-13 requested changes

2020-11-18 10:07 UTC, justyna-13 commented on packages/vue/docs/releases/v0.9.3.md
> +# Latest version - v0.9.2 🎉
this file is called v0.9.3 and here is v0.9.2

2020-12-14 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1533) before we can accept your contribution.<br/><hr/>**Adam Pawliński** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1533) it.</sub>

2020-12-27 09:12 UTC, mayashavin approved these changes

2021-01-05 14:16 UTC, merged