fix: storybook change docs rendering to iframe on few components
vuestorefront/storefront-ui pull request #1646
Opened 2021-01-19 09:07 UTC by AdamPawlinski

# Related issue
Closes #1644 

# Scope of work
Change the way of rendering docs to iframe on:
SfOverlay, SfBottomModal, SfDropdown, SfModal. Styling need to be fixed.

# Screenshots of visual changes
![image](https://user-images.githubusercontent.com/32042425/105012111-0f886000-5a3e-11eb-9b67-fff4a9790f5a.png)

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-01-19 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1646) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1646) before we can accept your contribution.<br/><hr/>**adampawlinski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1646) it.</sub>

2021-01-19 09:17 UTC, justyna-13 approved these changes

2021-02-01 09:40 UTC, mayashavin requested changes
See my comments

2021-02-01 09:40 UTC, mayashavin commented on packages/vue/src/components/molecules/SfModal/SfModal.stories.js
> +Common.parameters = {
you dont need this if the main is already defined above.

2021-07-02 12:08 UTC, justyna-13 approved these changes

2021-07-05 08:01 UTC, Baroshem approved these changes
Like

2021-07-05 08:09 UTC, merged