fix: sfheader mobile navigation
vuestorefront/storefront-ui pull request #1657
Opened 2021-01-20 23:13 UTC by AdamPawlinski

# Related issue
Closes #1635

# Scope of work
Fix style for mobile navigation modifier and isNavVisable prop. 
Add menuItem for mobile to story. 

# Screenshots of visual changes
![image](https://user-images.githubusercontent.com/32042425/105252311-752f3600-5b7d-11eb-8380-5757904592cf.png)

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-01-20 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1657) before we can accept your contribution.<br/><hr/>**adampawlinski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1657) it.</sub>

2021-01-21 08:38 UTC, mayashavin requested changes

2021-01-21 08:38 UTC, mayashavin commented on packages/shared/styles/components/organisms/SfHeader.scss
> +      display: var(--header-navigation-display, flex);
remove `--header-navigation-display`, use `flex` only

2021-01-21 08:38 UTC, mayashavin commented on packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
> +      <template slot="mobile-navigation-item">
Why do we want `SfMenuItem`? Any specific reason? If nothing special, please use `SfLink` is enough

2021-01-25 14:35 UTC, AdamPawlinski commented
I changed base branch to develop as this change is not so relevant to be included in hotfix.

2021-02-01 09:48 UTC, mayashavin commented
Will merge once v.10.1 is merged

2021-02-01 09:48 UTC, mayashavin submitted a review, later dismissed

2021-02-03 16:18 UTC, mayashavin approved these changes

2021-02-03 16:18 UTC, merged