fix: remove css image dimension
vuestorefront/storefront-ui pull request #1695
Opened 2021-02-12 08:33 UTC by AdamPawlinski

# Related issue
Closes #1662 

# Scope of work
SfProductCard - remove css image dimention properties to allow setting them by props.

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-02-12 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1695) before we can accept your contribution.<br/><hr/>**AdamPawlinski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1695) it.</sub>

2021-02-12 09:20 UTC, justyna-13 requested changes
See SfProductCard on mobile view with these changes :)

2021-06-10 12:40 UTC, Baroshem commented
Let's create a pull request for hotfix-0.10.8 for this bugfix @AdamPawlinski :)

2021-07-09 12:16 UTC, Baroshem commented
Closing in favor of #1908

2021-07-09 12:16 UTC, closed without merging