feat: open tabs not only by clicking on SfTab
vuestorefront/storefront-ui pull request #1743
Opened 2021-03-17 13:47 UTC by justyna-13

# Related issue

Closes #

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-03-18 09:36 UTC, AdamPawlinski commented
@justyna-13 according tome solution can be to add emit event in toggle function in SfTabs and then listen to it in story like this:
SfTabs
```toggle(id) {
      this.$children.forEach((child) => {
        child._uid === id ? (child.isActive = true) : (child.isActive = false);        
      });
      const active = this.$children.findIndex(
        child => child.isActive === true
      ) + 1;
      this.$emit('click:tab', active)
    },
```
story: 
```
<SfTabs
    :open-tab="open"
    :tabMaxContentHeight="tabMaxContentHeight"
    :tabShowText="tabShowText"
    :tabHideText="tabHideText"
    @click:tab="change"
  >
    <SfTab
        v-for="tab in tabs"
        :key="tab.title"
        :title="tab.title"
    >
        {{tab.content}}
    </SfTab>
  </SfTabs>
```

Let me know what you think?

2021-03-18 13:33 UTC, Baroshem commented on packages/vue/src/components/organisms/SfTabs/SfTabs.vue
> +        child._uid === id ? (child.isActive = true) : (child.isActive = false);
```suggestion
        child.isActive = child._uid === id;
```

2021-03-18 13:34 UTC, Baroshem commented on packages/vue/src/components/organisms/SfTabs/SfTabs.vue
> +      const active =
Maybe change name of the variable to something connected to index? I.e
```suggestion
      const activeTabId =
```

2021-03-18 13:34 UTC, Baroshem requested changes
Well done, it works now!

Some small suggestions from my side ;)

2021-03-18 14:10 UTC, AdamPawlinski approved these changes
I have no questions here. Maybe we can add this new behaviour to the product example. After clicking on "read all reviews" button the "read reviews" button could be opened. But we can do it in separate issue. Wdyt @justyna-13?

2021-03-19 09:58 UTC, Baroshem approved these changes

2021-03-22 09:43 UTC, merged