Feat #1763/remove unused libs  master
vuestorefront/storefront-ui pull request #1795
Opened 2021-05-06 07:59 UTC by Baroshem

# Related issue

Closes #1763 

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-05-06 12:06 UTC, justyna-13 requested changes
I think something went wrong with tabs :) 
![Screenshot from 2021-05-06 14-00-47](https://user-images.githubusercontent.com/46591755/117295306-f7fda780-ae73-11eb-8ffc-93ad2cb48f27.png)
Also would be good not to lose a nice look of scrollbar :) 
![Screenshot from 2021-05-06 14-02-31](https://user-images.githubusercontent.com/46591755/117295413-1a8fc080-ae74-11eb-870b-4fa130cbce85.png)

2021-05-12 10:11 UTC, AdamPawlinski reviewed
Just a few questions.
Regarding scrollable, can we get rid of the simplebar import from scss and `simplebar-scrollbar:before` properties as they are not longer needed? And I think, like Justyna, that we can make another issue for styling scrollbar to leave it like before. 

We could also remove folder with vuepress stuff, wdyt? 
![image](https://user-images.githubusercontent.com/32042425/117957943-d3457c00-b31a-11eb-9b83-cf4945232f01.png)


I wonder about adding vue as the dependency, if it's necessary, can we add it to devDependencies?

2021-05-17 09:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=1795) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Baroshem<br/>:x: Jakub Andrzejewski<br/><hr/>**Jakub Andrzejewski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=1795) it.</sub>

2021-05-17 09:47 UTC, justyna-13 approved these changes
:+1:

2021-05-17 09:47 UTC, justyna-13 commented on packages/shared/styles/components/molecules/SfScrollable.scss
> +    background-color: #fff;
`--c-white`

2021-05-17 09:47 UTC, justyna-13 commented on packages/shared/styles/components/molecules/SfScrollable.scss
> +    width: 16px;
`--spacer-sm`

2021-05-18 08:07 UTC, merged