fix: remove unused badge props from SfCircleIcon
vuestorefront/storefront-ui pull request #2015
Opened 2021-09-22 17:38 UTC by VanessaKeeton

# Related issue
https://github.com/vuestorefront/storefront-ui/issues/1754
Closes #1754

# Scope of work
Removed unused badge props.

# Screenshots of visual changes
N/A

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2021-09-22 17:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=2015) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/storefront-ui?pullRequest=2015) before we can accept your contribution.<br/><hr/>**Vanessa Keeton** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/storefront-ui?pullRequest=2015) it.</sub>

2021-09-24 05:39 UTC, justyna-13 submitted a review, later dismissed
Good job @VanessaKeeton :+1:

2021-09-24 07:06 UTC, Baroshem requested changes
Hi @VanessaKeeton 

Can you please add a changelog entry for this change in `storefront-ui/packages/vue/src/stories/releases/v0.11.x/v0.11.0/v0.11.0.stories.mdx`?

2021-09-27 21:20 UTC, VanessaKeeton commented
@Baroshem - I've added this fix to the changelog. Please let me know if the formatting is ok. It's my first time contributing and I am learning the process. :)

2021-09-28 06:08 UTC, justyna-13 approved these changes

2021-09-28 06:18 UTC, Baroshem approved these changes

2021-09-28 06:39 UTC, merged